# The maximum amount of blocks changed before it stops (0 for infinite, which is rlly laggy)
maxaffectedblocks: 5000

# Whether or not blocks update each other at all (useful against lag and with autoupdates)
chainupdates: true

# Whether or not the falling blocks landing can cause stuff to fall (a bit laggy)
fallingblocksupdate: true

# Whether or not projectiles can cause updates when they land
projectilesupdate: true

# Whether or not things like flowers and slabs will break falling blocks
unsolidblocksbreakfbs: false

# Distance from players that blocks autoupdate (0 to disable)
autoupdatedistance: 5

# Whether or not explosions have realistic qualities to them
realisticexplosions: true

# The default value for players to view realistic particles from explosions
explosionparticlesdefault: true

# Whether or not explosions update nearby blocks (excluding blocks flung from it) (requires realisticexplosions to be true)
explosionupdates: true

# Whether or not you can shift click to ignore block physics on the the block placed
shiftignorephysics: true