name: Block-Physics
main: me.hypercodec.physics.Main
version: 1.6
author: HyperCodec
api-version: 1.18
description: "Makes blocks act like sand"

permissions:
  blockphysics.*:
    blockphysics.shiftclick: true

  blockphysics.shiftclick:
    default: true